spring:
  redis:
    pool:
      min-idle: 0
      max-idle: 8
      max-active: 8
      port: 6379
      host: 127.0.0.1
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/thingspire
    username: postgres
    password: 1234
    hikari:
      poolName: Hikari
      auto-commit: false