spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/thingspire
    username: postgres
    password: 1234
    hikari:
      poolName: Hikari
      auto-commit: false


