
spring:
#  redis:
#    port: 6379
#    host: localhost
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/thingspire
    username: postgres
    password: 1234
    hikari:
      poolName: Hikari
      auto-commit: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true



  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql:

# JWT
jwt:
  key: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQ=
  access-token-expiration-minutes: 180
  refresh-token-expiration-minutes: 43200

password:
  reset: thingspire